Enquete/Enquete/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
]

Enquete/main/urls.py
from django.urls import path
from . import views


app_name = 'main'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('enquete/<int:pk>/', views.DetalhesView.as_view(), name='detalhes'),
    path('enquete/<int:pk>/comentario', views.ComentarioView.as_view(), name='comentario'),
    path('enquete/<int:pk>/resultado', views.ResultadoView.as_view(), name='resultado'),
    path('enquete/<int:id_enquete>/votacao', views.votacao, name='votacao'),
    ]

Enquete/main/models.py
from django.db import models
from django.utils import timezone
import datetime

class Usuario(models.Model):
    login = models.CharField(max_length=50)
    senha = models.CharField(max_length=50)
    email = models.CharField(max_length=100)
    def __str__(self):
        return self.login

class Pergunta(models.Model):
    texto_pergunta = models.CharField(max_length=200)
    data_de_publicacao = models.DateTimeField('Data de publicação')
    autor = models.ForeignKey(Usuario, on_delete=models.CASCADE, default = None, null=True)
    def __str__(self):
        return self.texto_pergunta
    def publicada_recentemente(self):
        agora = timezone.now()
        return agora-datetime.timedelta(days=1) <=self.data_de_publicacao <= agora
    publicada_recentemente.admin_order_field = 'data_de_publicacao'
    publicada_recentemente.boolean = True
    publicada_recentemente.short_description = 'Últimas 24H?'

class Opcao(models.Model):
    texto_opcao = models.CharField(max_length=200)
    votos = models.IntegerField(default=0)
    pergunta = models.ForeignKey(Pergunta, on_delete=models.CASCADE)
    def __str__(self):
        return self.texto_opcao

class Comentario(models.Model):
    pergunta_cometario = models.ForeignKey(Pergunta, related_name="comentarios", on_delete=models.CASCADE)
    nome_do_autor = models.CharField(max_length=255)
    texto = models.TextField()
    data_de_insercao = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.nome_do_autor

Enquete/main/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from .models import Pergunta, Opcao, Comentario

# Create your views here.
class IndexView(generic.ListView):
    def get_queryset(self):
        return Pergunta.objects.filter(data_de_publicacao__lte=timezone.now()).order_by('-data_de_publicacao')[:5]

class DetalhesView(generic.DetailView):
    model = Pergunta
    def get_queryset(self):
        return Pergunta.objects.filter(data_de_publicacao__lte=timezone.now())

class ComentarioView(generic.DetailView):
    model = Comentario
    template_name = 'main/comentario_detail.html'

class ResultadoView(generic.DetailView):
    model = Pergunta
    template_name = 'main/resultado.html'

def votacao(request, id_enquete):
    pergunta = get_object_or_404(Pergunta, pk=id_enquete)
    try:
        opcao_selecionada = pergunta.opcao_set.get(pk=request.POST['opcao'])
    except (KeyError, Opcao.DoesNotExist):
        return render (request, 'main:pergunta_detail.html', { 'pergunta':pergunta, 'error_message': "Selecione uma opção VÁLIDA"})
    else:
        opcao_selecionada.votos += 1
        opcao_selecionada.save()
        return HttpResponseRedirect(reverse('main:resultado', args=(pergunta.id,)))

Enquete/main/templates/main/comentario_detail.html
<!DOCTYPE html>
<html>
    <head>
        <title>App Enquete - Detalhes do comentário</title>
        <meta charset="utf-8"/>
    </head>
    <body>
        <h2>Detalhes do comentário</h2>
        <strong>
            {{ comentario.nome_do_autor }} -
            {{ comentario.data_de_insercao }}
        </strong>
        </br>
        {{ comentario.texto }}
        </br>
        <hr>
        <p>(<a href="{% url 'main:detalhes' comentario.id %}">voltar para a pergunta {{ pergunta.id }}</a>)</p>
        <p>(<a href="{% url 'main:index' %}">voltar para a lista de perguntas</a>)</p>
    </body>
</html>

Enquete/main/templates/main/pergunta_detail.html
<!DOCTYPE html>
<html>
    <head>
        <title>App Enquete - Detalhes</title>
        <meta charset="utf-8"/>
    </head>
    <body>
        <h2>Detalhes da enquete {{ pergunta.id }}</h2>
        <u>Pergunta</u>: {{ pergunta.texto_pergunta }}<br/>
        <u>Data de publicação</u>: {{ pergunta.data_de_publicacao}}
        {% if error_message %}
            <hr/>
            <strong>{{ error_message }}</strong>
            <hr/>
        {% endif %}
        <form action="{% url 'main:votacao' pergunta.id %}" method="post">
            {% csrf_token %}
            <ul>
                {% for opcao in pergunta.opcao_set.all %}
                    <li><input type="radio" name="opcao"
                        id="opcao{{ forloop.counter }}" value="{{ opcao.id }}">
                        <label for="opcao{{ forloop.counter }}">
                            {{ opcao.texto_opcao }}
                        </label>
                    </li>
                {% endfor %}
            </ul>
            <input type="submit" value="Registre o seu voto">
        </form>
        </br>
        <h2>Comentários...</h2>
                {% if not pergunta.comentarios.all %}
                    <p>Nenhum comentário adicionado...</p>
                {% else %}
                    {% for comentario in pergunta.comentarios.all %}
                        </br>
                        <a href="{% url 'main:comentario' pergunta.id %}">{{ comentario.texto }}</a>
                        </br>
                        <hr>
                    {% endfor %}
                {% endif %}
    </body>
</html>

Enquete/main/templates/main/pergunta_list.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>App enquete</title>
	<meta charset="utf-8">
	<link rel="stylesheet" type="text/css" href="{% static 'main/style.css' %}">
</head>
<body>
	{% if pergunta_list %}
		<h2>Lista de últimas enquetes</h2>
		<ul>
			{% for pergunta in pergunta_list %}
				<li><a href="{% url 'main:detalhes' pergunta.id %}">
				    {{ pergunta.texto_pergunta }}
				</a>(<a href="{% url 'main:resultado' pergunta.id %}">Ver parcial</a>)</li>
			{% endfor %}
		</ul>
	{% else %}
		<h3>Não há enquetes cadastradas até o momento!</h3>
	{% endif %}
</body>
</html>

Enquete/main/templates/main/resultado.html
<!DOCTYPE html>
<html>
    <head>
        <title> App Enquete - resultados </title>
    </head>
    <body>
        <h2>Resultado parcial da enquente {{pergunta.id}}</h2>
        <u>Pergunta</u>: {{ pergunta.texto_pergunta }}<br/>
        <u>Data de publicação</u>: {{ pergunta.data_de_publicacao}}
            <ul>
                {% for opcao in pergunta.opcao_set.all %}
                    <li> {{ opcao.texto_opcao }} = {{opcao.votos}} voto{{ opcao.votos | pluralize }}</li>
                {% endfor %}
            </ul>
        <hr/>
        <a href="{% url 'main:detalhes' pergunta.id %}" > Deseja votar novamente?</a>
    </body>
</html>